name: Checkmarx Scan with Tags

on:
  push:
    branches:
      - main

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures we get all commit history and tags

      - name: Fetch the latest tag
        id: fetch_latest_tag
        run: |
          git fetch --tags
          # Get the most recent tag by creation date
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Checkmarx AST GitHub Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: "--tags ${{ env.latest_tag }}"
