trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: __default
    jobs:
      - job: UbuntuCheckmarxJob
        displayName: 'Checkmarx Scan on Ubuntu'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Download and extract latest Checkmarx One CLI
          - task: Bash@3
            displayName: 'Download and Extract Checkmarx CLI (Ubuntu)'
            inputs:
              targetType: 'inline'
              script: |
                curl -LO https://download.checkmarx.com/CxOne/CLI/latest/ast-cli_linux_x64.tar.gz
                mkdir -p CxONE_CLI
                tar -xzf ast-cli_linux_x64.tar.gz -C CxONE_CLI
                rm ast-cli_linux_x64.tar.gz
                chmod +x CxONE_CLI/cx

          # Run Checkmarx CLI Scan
          - task: Bash@3
            displayName: 'Run Checkmarx CLI Scan (Ubuntu)'
            inputs:
              targetType: 'inline'
              script: |
                ./CxONE_CLI/cx scan create \
                  --project-name "$(Build.Repository.Name)" \
                  -s "$(Build.SourcesDirectory)" \
                  --branch "$(Build.SourceBranchName)" \
                  --apikey $(CX_API_KEY)
