trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: __default
    jobs:
      - job: UbuntuCheckmarxJob
        displayName: 'Checkmarx Scan on Ubuntu'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Linux setup
          - task: Bash@3
            displayName: 'Download and Extract Checkmarx CLI (Ubuntu)'
            inputs:
              targetType: 'inline'
              script: |
                curl -LO https://github.com/Checkmarx/ast-cli/releases/download/2.3.0/ast-cli_2.3.0_linux_x64.tar.gz
                mkdir CxONE_CLI
                tar -xzf ast-cli_2.3.0_linux_x64.tar.gz -C CxONE_CLI
                rm ast-cli_2.3.0_linux_x64.tar.gz

          # Run Checkmarx CLI Scan for Ubuntu
          - task: Bash@3
            displayName: 'Run Checkmarx CLI Scan (Ubuntu)'
            inputs:
              targetType: 'inline'
              script: |
                ./CxONE_CLI/cx scan create --project-name "$(Build.Repository.Name)" -s "$(Build.SourcesDirectory)" --branch "$(Build.SourceBranchName)" --apikey <your api key>